#!/bin/bash

source ./.git/hooks/include.sh

# Validates whether commit message is of a certain format.
# Aborts commit if message is unsatisfactory
message=$1

print_important "Commit message format check"

error_message="Aborting commit. Please ensure your commit message meets the
               standard requirement. '${commit_format_example}'
              Use '${commit_message_example}' for reference"


# @TODO: for POSIX-compliant systems, this could be used instead:
#if ! grep -iqE ^$commit_standard_regex$ "${message}"; then

# for non-POSIX systems:
if [[ ${message} =~ ^$commit_standard_regex$ ]]; then
    print_success "Committing the changes"
else
    print_error "$error_message" >&2
    exit 1
fi
