#!/bin/bash

source ./.git/hooks/include.sh

# Make sure you have installed ESlint

print_important "Pre-commit code check"

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# ESlint test (Javascript)
ESLINT="node_modules/.bin/eslint"
pwd

if [[ ! -x "$ESLINT" ]]; then
  print_error "Please install ESlint"
  print "(npm install eslint)\n"
  exit 1
fi


# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 "$PROJECT/$FILE"
    if [ $? != 0 ]; then
        print_error "Fix the error before commit."
        #exit 1
    else
        print_success "Code is well written. Nice coding! [OK]"
    fi
    FILES="$FILES \"$PROJECT/$FILE\""
done

if [ -f "$PROJECT/phpcs.ruleset.xml" ]
then
    RULESET="$PROJECT/phpcs.ruleset.xml"
elif [ -f "$PROJECT/phpcs.xml.dist" ]
then
    RULESET="$PROJECT/phpcs.xml.dist"
else
    RULESET="WordPress"
fi

echo "Checking Code Standard Compliance, using $RULESET as ruleset standard..."
for FILE in $SFILES
do
    ./vendor/bin/phpcs --standard="$RULESET" --colors --encoding=utf-8 -n -p "$PROJECT/$FILE"
    if [ $? != 0 ]; then
        print_error "Fix the error before commit."
        print "Run"
        print "  ./vendor/bin/phpcbf --standard=\"$RULESET\" $FILES"
        print "for automatic fix or fix it manually."
        #exit 1
    else
        print_success "Code is well written. Nice coding! [OK]"
    fi
done

# JavaScript (React) testing.
print_important "ESlint JS Tests"

#STAGED_FILES_CMD=($(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$"))
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.js`

print_important "ESLint'ing ${#STAGED_FILES_CMD[@]} files"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

$ESLINT "${STAGED_FILES[@]}" --fix

ESLINT_EXIT="$?"

# Re-add files since they may have been fixed
git add "${STAGED_FILES[@]}"

if [[ "${ESLINT_EXIT}" == 0 ]]; then
  print_success "COMMIT SUCCEEDED"
else
  print_error "COMMIT FAILED:"
  print "Fix eslint errors and try again"
  exit 1
fi

print_success "Code check completed."

exit $?
