#!/bin/bash

# Result will be output in place of the default commit message on running git commit
current_branch=`git rev-parse --abbrev-ref HEAD`

echo "#$current_branch Note: commit messages should be of the form: [#StoryID:CommitType] Commit Message." > $1
